spring:
  application:
    name: gateway-service-kjh


  profiles:
    #    group: # 개별 profile 내 logging.config 설정으로 이용 해 주세요.
    #      dev: "LOG_CONSOLE,LOG_FILE"
    #      prd: "LOG_CONSOLE,LOG_FILE"
    #      local: "LOG_CONSOLE,LOG_FILE"
    #      pc: "LOG_CONSOLE,LOG_FILE"
    #    active: dev
    #    active: prod
    active: local

server:
  port: 20001

hystrix.command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMiliseconds: 200 # {timeout}시간
      metrics:
        rollingStats:
          timeInMilliseconds: 50000 # {최근 통계시간}
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 3 # {최소요청횟수} , circuit breaker 오픈 여부를 판단할 최소 request 수
        errorThresholdPercentage: 50 # {실패율} , circuit breaker 오픈 여부를 판단할 실패 횟수 (default: 50%)
        sleepWindowInMiliseconds: 5000 # {Circuit Breaker 유지 시간} , circuit breaker 지속 시간 (default: 5000ms)


management:
  server:
    port: 20002
  endpoints:
    web:
      base-path: /
    shutdown:
      enabled: true
    health:
      show-details: always    #actuator에서 디테일한 정보 확인을 위함
  health:
    circuitbreakers:
      enabled: true  #actuator를 통해 circuitbreaker 상태를 확인하기 위함


---

spring:
  config:
    activate:
      on-profile: local
    import: "application-local.yml"

---

spring:
  config:
    activate:
      on-profile: dev
    import: "application-dev.yml"


---

spring:
  config:
    activate:
      on-profile: prod
    import: "application-prod.yml"